# Site settings
title:            Doa's Blog
email:            pearl097@naver.com
description:      Resume
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pearl0725.github.io" # the base hostname & protocol for your site

#twitter_username: pearl0725
github_username:  pearl0725

# Build settings
markdown:         kramdown
